name: Daily build

on:
  schedule:
    - cron: "30 0 * * *"

jobs:
  call_workflow:
    name: Run Daily Build Workflow
    if: ${{ github.repository_owner == 'ballerina-platform' }}
    uses: ballerina-platform/ballerina-library/.github/workflows/daily-build-connector-template.yml@2201.10.x
    secrets: inherit
    with:
      repo-name: module-ballerinax-confluent.cavroserdes
